FROM buildpack-deps:trixie

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Create user and set home, with sudo access
ARG USERNAME=devcontainer
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
  #
  # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
  && apt-get update \
  && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME

# Things to install:
# Install Debian packages
ARG APT_GET_PACKAGES="curl" # Just put something so it doesn't fail
RUN apt-get install -y \
  gawk \
  fish \
  $APT_GET_PACKAGES \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*


USER $USERNAME
ENV HOME=/home/$USERNAME
# Install mise
ARG MISE_PACKAGES=""
RUN curl https://mise.run | sh && \
  ~/.local/bin/mise use --global \
  fd@latest \
  eza@latest \
  ripgrep@latest \
  atuin@latest \
  starship@latest \
  zoxide@latest \
  lazygit@latest \
  neovim@latest \
  node@22.18.0 \
  python@3.13 \
  chezmoi@latest
RUN ~/.local/bin/mise use --global $MISE_PACKAGES
